name: Build ForceCriminalMenu
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Theos
        uses: NyaMisty/theos-action@master
        with:
          packages: "ForceCriminalMenu"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ForceCriminalMenu
          path: packages/
